"""add ondelete cascade to all foreign keys

Revision ID: 1edca5c1893a
Revises: 8b599b08e052
Create Date: 2026-02-17 12:14:30.657759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1edca5c1893a'
down_revision: Union[str, None] = '8b599b08e052'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('book_authors_author_id_fkey'), 'book_authors', type_='foreignkey')
    op.drop_constraint(op.f('book_authors_book_id_fkey'), 'book_authors', type_='foreignkey')
    op.create_foreign_key(None, 'book_authors', 'authors', ['author_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'book_authors', 'books', ['book_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('list_books_book_id_fkey'), 'list_books', type_='foreignkey')
    op.drop_constraint(op.f('list_books_list_id_fkey'), 'list_books', type_='foreignkey')
    op.create_foreign_key(None, 'list_books', 'books', ['book_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'list_books', 'lists', ['list_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('lists_user_id_fkey'), 'lists', type_='foreignkey')
    op.create_foreign_key(None, 'lists', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('ratings_user_id_fkey'), 'ratings', type_='foreignkey')
    op.drop_constraint(op.f('ratings_book_id_fkey'), 'ratings', type_='foreignkey')
    op.create_foreign_key(None, 'ratings', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'ratings', 'books', ['book_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('reviews_book_id_fkey'), 'reviews', type_='foreignkey')
    op.drop_constraint(op.f('reviews_user_id_fkey'), 'reviews', type_='foreignkey')
    op.create_foreign_key(None, 'reviews', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'reviews', 'books', ['book_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.create_foreign_key(op.f('reviews_user_id_fkey'), 'reviews', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('reviews_book_id_fkey'), 'reviews', 'books', ['book_id'], ['id'])
    op.drop_constraint(None, 'ratings', type_='foreignkey')
    op.drop_constraint(None, 'ratings', type_='foreignkey')
    op.create_foreign_key(op.f('ratings_book_id_fkey'), 'ratings', 'books', ['book_id'], ['id'])
    op.create_foreign_key(op.f('ratings_user_id_fkey'), 'ratings', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'lists', type_='foreignkey')
    op.create_foreign_key(op.f('lists_user_id_fkey'), 'lists', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'list_books', type_='foreignkey')
    op.drop_constraint(None, 'list_books', type_='foreignkey')
    op.create_foreign_key(op.f('list_books_list_id_fkey'), 'list_books', 'lists', ['list_id'], ['id'])
    op.create_foreign_key(op.f('list_books_book_id_fkey'), 'list_books', 'books', ['book_id'], ['id'])
    op.drop_constraint(None, 'book_authors', type_='foreignkey')
    op.drop_constraint(None, 'book_authors', type_='foreignkey')
    op.create_foreign_key(op.f('book_authors_book_id_fkey'), 'book_authors', 'books', ['book_id'], ['id'])
    op.create_foreign_key(op.f('book_authors_author_id_fkey'), 'book_authors', 'authors', ['author_id'], ['id'])
    # ### end Alembic commands ###
