"""simplify schema add similar_books and author external_id

Revision ID: 38ec2ea211e9
Revises: e6b076b11888
Create Date: 2026-02-15 14:25:40.161448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38ec2ea211e9'
down_revision: Union[str, None] = 'e6b076b11888'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authors', sa.Column('external_id', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_authors_external_id'), 'authors', ['external_id'], unique=True)
    op.drop_column('authors', 'average_rating')
    op.drop_column('authors', 'ratings_count')
    op.drop_column('authors', 'text_reviews_count')
    op.add_column('books', sa.Column('similar_books', sa.Text(), nullable=True))
    op.drop_column('books', 'link')
    op.drop_column('books', 'is_ebook')
    op.drop_column('books', 'isbn')
    op.drop_column('books', 'media_type')
    op.drop_column('books', 'num_pages')
    op.drop_column('books', 'isbn13')
    op.drop_column('books', 'country_code')
    op.drop_column('books', 'url')
    op.drop_column('books', 'publisher_name')
    op.drop_column('books', 'num_reviews')
    op.drop_column('books', 'ratings_count')
    op.drop_column('books', 'average_rating')
    op.drop_column('books', 'kindle_asin')
    op.drop_column('books', 'asin')
    op.drop_column('books', 'publisher')
    op.drop_column('books', 'language_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('language_code', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('books', sa.Column('publisher', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('books', sa.Column('asin', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('books', sa.Column('kindle_asin', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('books', sa.Column('average_rating', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('books', sa.Column('ratings_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('books', sa.Column('num_reviews', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('books', sa.Column('publisher_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('books', sa.Column('url', sa.VARCHAR(length=1000), autoincrement=False, nullable=True))
    op.add_column('books', sa.Column('country_code', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('books', sa.Column('isbn13', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('books', sa.Column('num_pages', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('books', sa.Column('media_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('books', sa.Column('isbn', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('books', sa.Column('is_ebook', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('books', sa.Column('link', sa.VARCHAR(length=1000), autoincrement=False, nullable=True))
    op.drop_column('books', 'similar_books')
    op.add_column('authors', sa.Column('text_reviews_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('authors', sa.Column('ratings_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('authors', sa.Column('average_rating', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_authors_external_id'), table_name='authors')
    op.drop_column('authors', 'external_id')
    # ### end Alembic commands ###
