"""drop stale rating_dist columns from books

Revision ID: 64894b366f6f
Revises: 6c9fc7128024
Create Date: 2026-02-18 15:02:52.418727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64894b366f6f'
down_revision: Union[str, None] = '6c9fc7128024'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'rating_dist_1')
    op.drop_column('books', 'rating_dist_total')
    op.drop_column('books', 'rating_dist_2')
    op.drop_column('books', 'rating_dist_5')
    op.drop_column('books', 'rating_dist_3')
    op.drop_column('books', 'rating_dist_4')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('rating_dist_4', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('books', sa.Column('rating_dist_3', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('books', sa.Column('rating_dist_5', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('books', sa.Column('rating_dist_2', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('books', sa.Column('rating_dist_total', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('books', sa.Column('rating_dist_1', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
