"""

Revision ID: 9913db3ab380
Revises: 51f5ee597203
Create Date: 2026-02-09 11:43:52.715616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9913db3ab380'
down_revision: Union[str, None] = '51f5ee597203'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authors', sa.Column('average_rating', sa.Float(), nullable=True))
    op.add_column('authors', sa.Column('ratings_count', sa.Integer(), nullable=True))
    op.add_column('authors', sa.Column('text_reviews_count', sa.Integer(), nullable=True))
    op.add_column('books', sa.Column('text_reviews_count', sa.Integer(), nullable=True))
    op.add_column('books', sa.Column('ratings_count', sa.Integer(), nullable=True))
    op.add_column('books', sa.Column('ratings_sum', sa.Integer(), nullable=True))
    op.add_column('books', sa.Column('books_count', sa.Integer(), nullable=True))
    op.add_column('books', sa.Column('media_type', sa.String(length=50), nullable=True))
    op.add_column('books', sa.Column('best_book_id', sa.String(length=50), nullable=True))
    op.add_column('books', sa.Column('work_id', sa.String(length=50), nullable=True))
    op.add_column('books', sa.Column('original_language_id', sa.String(length=50), nullable=True))
    op.add_column('books', sa.Column('default_description_language_code', sa.String(length=10), nullable=True))
    op.add_column('books', sa.Column('default_chaptering_book_id', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'default_chaptering_book_id')
    op.drop_column('books', 'default_description_language_code')
    op.drop_column('books', 'original_language_id')
    op.drop_column('books', 'work_id')
    op.drop_column('books', 'best_book_id')
    op.drop_column('books', 'media_type')
    op.drop_column('books', 'books_count')
    op.drop_column('books', 'ratings_sum')
    op.drop_column('books', 'ratings_count')
    op.drop_column('books', 'text_reviews_count')
    op.drop_column('authors', 'text_reviews_count')
    op.drop_column('authors', 'ratings_count')
    op.drop_column('authors', 'average_rating')
    # ### end Alembic commands ###
