"""

Revision ID: e6b076b11888
Revises: ef0cc65c3f0d
Create Date: 2026-02-15 13:56:02.732372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6b076b11888'
down_revision: Union[str, None] = 'ef0cc65c3f0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'best_book_id')
    op.drop_column('books', 'publication_day')
    op.drop_column('books', 'edition_information')
    op.drop_column('books', 'role')
    op.drop_column('books', 'ratings_sum')
    op.drop_column('books', 'name')
    op.drop_column('books', 'pages_number')
    op.drop_column('books', 'original_language_id')
    op.drop_column('books', 'element')
    op.drop_column('books', 'format')
    op.drop_column('books', 'count')
    op.drop_column('books', 'default_description_language_code')
    op.drop_column('books', 'title_without_series')
    op.drop_column('books', 'publication_month')
    op.drop_column('books', 'books_count')
    op.drop_column('books', 'text_reviews_count')
    op.drop_column('books', 'default_chaptering_book_id')
    op.drop_column('books', 'work_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('work_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('books', sa.Column('default_chaptering_book_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('books', sa.Column('text_reviews_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('books', sa.Column('books_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('books', sa.Column('publication_month', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('books', sa.Column('title_without_series', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('books', sa.Column('default_description_language_code', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('books', sa.Column('count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('books', sa.Column('format', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('books', sa.Column('element', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('books', sa.Column('original_language_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('books', sa.Column('pages_number', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('books', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('books', sa.Column('ratings_sum', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('books', sa.Column('role', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('books', sa.Column('edition_information', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('books', sa.Column('publication_day', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('books', sa.Column('best_book_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
