"""

Revision ID: ef0cc65c3f0d
Revises: 9913db3ab380
Create Date: 2026-02-10 16:02:13.100722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef0cc65c3f0d'
down_revision: Union[str, None] = '9913db3ab380'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('isbn', sa.String(length=20), nullable=True))
    op.add_column('books', sa.Column('isbn13', sa.String(length=20), nullable=True))
    op.add_column('books', sa.Column('asin', sa.String(length=20), nullable=True))
    op.add_column('books', sa.Column('kindle_asin', sa.String(length=20), nullable=True))
    op.add_column('books', sa.Column('title_without_series', sa.String(length=500), nullable=True))
    op.add_column('books', sa.Column('description', sa.String(), nullable=True))
    op.add_column('books', sa.Column('num_pages', sa.Integer(), nullable=True))
    op.add_column('books', sa.Column('publisher', sa.String(length=255), nullable=True))
    op.add_column('books', sa.Column('publication_day', sa.Integer(), nullable=True))
    op.add_column('books', sa.Column('publication_month', sa.Integer(), nullable=True))
    op.add_column('books', sa.Column('publication_year', sa.Integer(), nullable=True))
    op.add_column('books', sa.Column('average_rating', sa.Float(), nullable=True))
    op.add_column('books', sa.Column('is_ebook', sa.Boolean(), nullable=True))
    op.add_column('books', sa.Column('format', sa.String(length=50), nullable=True))
    op.add_column('books', sa.Column('edition_information', sa.String(length=255), nullable=True))
    op.add_column('books', sa.Column('language_code', sa.String(length=10), nullable=True))
    op.add_column('books', sa.Column('country_code', sa.String(length=10), nullable=True))
    op.add_column('books', sa.Column('url', sa.String(length=1000), nullable=True))
    op.add_column('books', sa.Column('link', sa.String(length=1000), nullable=True))
    op.add_column('books', sa.Column('image_url', sa.String(length=1000), nullable=True))
    op.add_column('books', sa.Column('book_id', sa.String(length=50), nullable=True))
    op.add_column('books', sa.Column('author_id', sa.String(length=50), nullable=True))
    op.add_column('books', sa.Column('role', sa.String(length=50), nullable=True))
    op.add_column('books', sa.Column('element', sa.String(length=50), nullable=True))
    op.add_column('books', sa.Column('count', sa.Integer(), nullable=True))
    op.add_column('books', sa.Column('name', sa.String(length=255), nullable=True))
    op.drop_column('books', 'publish_day')
    op.drop_column('books', 'publish_year')
    op.drop_column('books', 'publish_month')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('publish_month', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('books', sa.Column('publish_year', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('books', sa.Column('publish_day', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('books', 'name')
    op.drop_column('books', 'count')
    op.drop_column('books', 'element')
    op.drop_column('books', 'role')
    op.drop_column('books', 'author_id')
    op.drop_column('books', 'book_id')
    op.drop_column('books', 'image_url')
    op.drop_column('books', 'link')
    op.drop_column('books', 'url')
    op.drop_column('books', 'country_code')
    op.drop_column('books', 'language_code')
    op.drop_column('books', 'edition_information')
    op.drop_column('books', 'format')
    op.drop_column('books', 'is_ebook')
    op.drop_column('books', 'average_rating')
    op.drop_column('books', 'publication_year')
    op.drop_column('books', 'publication_month')
    op.drop_column('books', 'publication_day')
    op.drop_column('books', 'publisher')
    op.drop_column('books', 'num_pages')
    op.drop_column('books', 'description')
    op.drop_column('books', 'title_without_series')
    op.drop_column('books', 'kindle_asin')
    op.drop_column('books', 'asin')
    op.drop_column('books', 'isbn13')
    op.drop_column('books', 'isbn')
    # ### end Alembic commands ###
