"""
Fine-tune a multilingual DistilBERT for emotion classification on book reviews.

Uses pseudo-labels generated by MilaNLProc/xlm-emo-t (knowledge distillation).
Supports multiple languages since reviews are not all in English.

Features:
- MLflow experiment tracking
- Early stopping
- Confusion matrix visualization
- Per-class metrics (precision, recall, F1)
- Checkpoint management
- Reproducible training with seed control
"""

from __future__ import annotations

import argparse
import json
import logging
import os
import random
import sys
import time
from datetime import datetime
from pathlib import Path
from typing import Any, Optional

import evaluate
import matplotlib.pyplot as plt
import mlflow
import numpy as np
import pandas as pd
import seaborn as sns
import torch
from datasets import Dataset, DatasetDict
from dotenv import load_dotenv
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.model_selection import train_test_split
from transformers import (
    AutoModelForSequenceClassification,
    AutoTokenizer,
    DataCollatorWithPadding,
    EarlyStoppingCallback,
    Trainer,
    TrainingArguments,
)

# Add project root to path
project_root = Path(__file__).parent.parent
sys.path.insert(0, str(project_root))

# Load environment variables
env_path = project_root / ".env"
load_dotenv(env_path)

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(name)s - %(levelname)s - %(message)s",
)
logger = logging.getLogger(__name__)

# Emotion labels (Plutchik's 8 basic emotions from MilaNLProc/xlm-emo-t)
LABEL2ID = {
    "anger": 0,
    "anticipation": 1,
    "disgust": 2,
    "fear": 3,
    "joy": 4,
    "sadness": 5,
    "surprise": 6,
    "trust": 7,
}
ID2LABEL = {v: k for k, v in LABEL2ID.items()}
EMOTIONS = list(LABEL2ID.keys())


def get_device() -> str:
    """Detect best available device."""
    if torch.cuda.is_available():
        return "cuda"
    elif hasattr(torch.backends, "mps") and torch.backends.mps.is_available():
        return "mps"
    return "cpu"


def detect_runtime(num_workers_arg: int = -1) -> dict[str, Any]:
    """Detect runtime configuration based on available hardware."""
    device = get_device()

    if device == "cuda":
        torch.backends.cuda.matmul.allow_tf32 = True
        torch.backends.cudnn.allow_tf32 = True
        torch.backends.cudnn.benchmark = True
        pin_memory = True
        auto_workers = min(8, os.cpu_count() or 1)
        bf16 = torch.cuda.is_bf16_supported()
        fp16 = not bf16
    elif device == "mps":
        pin_memory = False
        auto_workers = 0
        bf16 = False
        fp16 = False
    else:
        pin_memory = False
        auto_workers = min(4, os.cpu_count() or 1)
        bf16 = False
        fp16 = False

    num_workers = auto_workers if num_workers_arg < 0 else num_workers_arg

    return {
        "device": device,
        "pin_memory": pin_memory,
        "num_workers": num_workers,
        "bf16": bf16,
        "fp16": fp16,
    }


def set_seed(seed: int) -> None:
    """Set random seeds for reproducibility."""
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)


def check_mlflow_env() -> bool:
    """Check that required MLflow environment variables are set."""
    required_vars = [
        "MLFLOW_TRACKING_URI",
        "MLFLOW_TRACKING_USERNAME",
        "MLFLOW_TRACKING_PASSWORD",
    ]
    missing = [v for v in required_vars if not os.getenv(v)]
    if missing:
        logger.warning(f"Missing MLflow environment variables: {missing}")
        return False
    return True


def compute_metrics(eval_pred) -> dict[str, float]:
    """Compute accuracy, F1, precision, recall for evaluation."""
    accuracy_metric = evaluate.load("accuracy")
    f1_metric = evaluate.load("f1")
    precision_metric = evaluate.load("precision")
    recall_metric = evaluate.load("recall")

    predictions, labels = eval_pred
    predictions = np.argmax(predictions, axis=1)

    acc = accuracy_metric.compute(predictions=predictions, references=labels)
    f1 = f1_metric.compute(predictions=predictions, references=labels, average="weighted")
    f1_macro = f1_metric.compute(predictions=predictions, references=labels, average="macro")
    precision = precision_metric.compute(predictions=predictions, references=labels, average="weighted")
    recall = recall_metric.compute(predictions=predictions, references=labels, average="weighted")

    return {
        "accuracy": acc["accuracy"],
        "f1_weighted": f1["f1"],
        "f1_macro": f1_macro["f1"],
        "precision": precision["precision"],
        "recall": recall["recall"],
    }


def plot_confusion_matrix(
    y_true: np.ndarray,
    y_pred: np.ndarray,
    labels: list[str],
    output_path: Path,
    normalize: bool = True,
) -> Path:
    """Generate and save confusion matrix plot."""
    cm = confusion_matrix(y_true, y_pred, normalize="true" if normalize else None)

    plt.figure(figsize=(12, 10))
    sns.heatmap(
        cm,
        annot=True,
        fmt=".2f" if normalize else "d",
        cmap="Blues",
        xticklabels=labels,
        yticklabels=labels,
    )
    plt.xlabel("Predicted")
    plt.ylabel("True")
    plt.title("Emotion Classification Confusion Matrix")
    plt.tight_layout()

    plot_path = output_path / "confusion_matrix.png"
    plt.savefig(plot_path, dpi=150)
    plt.close()

    return plot_path


def plot_class_distribution(
    df: pd.DataFrame,
    emotion_col: str,
    output_path: Path,
    title: str = "Emotion Distribution",
) -> Path:
    """Plot emotion class distribution."""
    plt.figure(figsize=(10, 6))
    counts = df[emotion_col].value_counts()
    sns.barplot(x=counts.index, y=counts.values, palette="viridis")
    plt.xlabel("Emotion")
    plt.ylabel("Count")
    plt.title(title)
    plt.xticks(rotation=45)
    plt.tight_layout()

    plot_path = output_path / "class_distribution.png"
    plt.savefig(plot_path, dpi=150)
    plt.close()

    return plot_path


def evaluate_on_test_set(
    trainer: Trainer,
    test_dataset: Dataset,
    output_dir: Path,
) -> dict[str, Any]:
    """Run comprehensive evaluation on test set."""
    logger.info("Running evaluation on test set...")

    # Get predictions
    predictions_output = trainer.predict(test_dataset)
    predictions = np.argmax(predictions_output.predictions, axis=1)
    labels = predictions_output.label_ids

    # Classification report
    report = classification_report(
        labels,
        predictions,
        target_names=EMOTIONS,
        output_dict=True,
    )

    # Save classification report
    report_path = output_dir / "classification_report.json"
    with open(report_path, "w") as f:
        json.dump(report, f, indent=2)
    logger.info(f"Classification report saved to {report_path}")

    # Print classification report
    print("\n" + "=" * 60)
    print("CLASSIFICATION REPORT")
    print("=" * 60)
    print(classification_report(labels, predictions, target_names=EMOTIONS))

    # Confusion matrix
    cm_path = plot_confusion_matrix(
        labels,
        predictions,
        EMOTIONS,
        output_dir,
    )
    logger.info(f"Confusion matrix saved to {cm_path}")

    # Per-class metrics
    per_class_metrics = {}
    for emotion in EMOTIONS:
        if emotion in report:
            per_class_metrics[emotion] = {
                "precision": report[emotion]["precision"],
                "recall": report[emotion]["recall"],
                "f1": report[emotion]["f1-score"],
                "support": report[emotion]["support"],
            }

    return {
        "test_accuracy": report["accuracy"],
        "test_f1_weighted": report["weighted avg"]["f1-score"],
        "test_f1_macro": report["macro avg"]["f1-score"],
        "test_precision_weighted": report["weighted avg"]["precision"],
        "test_recall_weighted": report["weighted avg"]["recall"],
        "per_class_metrics": per_class_metrics,
        "classification_report_path": str(report_path),
        "confusion_matrix_path": str(cm_path),
    }


def log_to_mlflow(
    args: argparse.Namespace,
    runtime: dict[str, Any],
    data_stats: dict[str, Any],
    training_time: float,
    test_metrics: dict[str, Any],
    output_path: Path,
    run_name: Optional[str] = None,
) -> str:
    """Log all training artifacts to MLflow."""
    logger.info("Logging to MLflow...")

    mlflow.set_tracking_uri(os.getenv("MLFLOW_TRACKING_URI", "https://mlflow.yousef.gg"))
    mlflow.set_experiment(args.experiment_name)

    with mlflow.start_run(run_name=run_name):
        # Log hyperparameters
        mlflow.log_params({
            "base_model": args.base_model,
            "batch_size": args.batch_size,
            "epochs": args.epochs,
            "learning_rate": args.learning_rate,
            "max_length": args.max_length,
            "max_samples_per_class": args.max_samples_per_class,
            "test_size": args.test_size,
            "val_size": args.val_size,
            "min_confidence": args.min_confidence,
            "warmup_ratio": args.warmup_ratio,
            "weight_decay": args.weight_decay,
            "early_stopping_patience": args.early_stopping_patience,
            "seed": args.seed,
        })

        # Log runtime config
        mlflow.log_params({
            "device": runtime["device"],
            "bf16": runtime["bf16"],
            "fp16": runtime["fp16"],
            "num_workers": runtime["num_workers"],
        })

        # Log data statistics
        mlflow.log_params({
            "total_samples": data_stats["total_samples"],
            "train_samples": data_stats["train_samples"],
            "val_samples": data_stats["val_samples"],
            "test_samples": data_stats["test_samples"],
        })

        # Log training time
        mlflow.log_metric("training_time_seconds", training_time)

        # Log test metrics
        for metric_name, value in test_metrics.items():
            if isinstance(value, (int, float)):
                mlflow.log_metric(metric_name, float(value))

        # Log per-class metrics
        if "per_class_metrics" in test_metrics:
            for emotion, metrics in test_metrics["per_class_metrics"].items():
                for metric_name, value in metrics.items():
                    if isinstance(value, (int, float)):
                        mlflow.log_metric(f"{emotion}_{metric_name}", float(value))

        # Log artifacts
        artifacts_to_log = [
            ("confusion_matrix.png", "plots"),
            ("class_distribution.png", "plots"),
            ("classification_report.json", "metrics"),
            ("training_config.json", "config"),
            ("data_stats.json", "stats"),
        ]

        for filename, artifact_path in artifacts_to_log:
            file_path = output_path / filename
            if file_path.exists():
                try:
                    mlflow.log_artifact(str(file_path), artifact_path=artifact_path)
                except Exception as e:
                    logger.warning(f"Could not log artifact {filename}: {e}")

        # Log model directory
        final_model_path = output_path / "final"
        if final_model_path.exists():
            try:
                mlflow.log_artifacts(str(final_model_path), artifact_path="model")
            except Exception as e:
                logger.warning(f"Could not log model artifacts: {e}")

        # Set tags
        mlflow.set_tags({
            "model_type": "EmotionClassifier",
            "framework": "transformers",
            "task": "text-classification",
            "training_date": datetime.now().isoformat(),
            "base_model": args.base_model,
        })

        run_id = mlflow.active_run().info.run_id
        logger.info(f"MLflow run ID: {run_id}")

        return run_id


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Fine-tune multilingual DistilBERT for emotion classification"
    )

    # Data arguments
    parser.add_argument(
        "--input",
        type=str,
        default="data/reviews_with_emotions.parquet",
        help="Input parquet file with emotion labels"
    )
    parser.add_argument(
        "--output-dir",
        type=str,
        default="models/emotion_classifier",
        help="Output directory for the fine-tuned model"
    )
    parser.add_argument(
        "--max-samples-per-class",
        type=int,
        default=300000,
        help="Maximum samples per emotion class (caps majority, keeps all minority)"
    )
    parser.add_argument(
        "--test-size",
        type=float,
        default=0.1,
        help="Proportion of data for test set"
    )
    parser.add_argument(
        "--val-size",
        type=float,
        default=0.1,
        help="Proportion of training data for validation"
    )
    parser.add_argument(
        "--min-confidence",
        type=float,
        default=0.5,
        help="Minimum emotion score to include sample"
    )

    # Model arguments
    parser.add_argument(
        "--base-model",
        type=str,
        default="distilbert-base-multilingual-cased",
        help="Base model to fine-tune"
    )
    parser.add_argument(
        "--max-length",
        type=int,
        default=256,
        help="Maximum sequence length"
    )

    # Training arguments
    parser.add_argument(
        "--epochs",
        type=int,
        default=3,
        help="Number of training epochs"
    )
    parser.add_argument(
        "--batch-size",
        type=int,
        default=16,
        help="Training batch size"
    )
    parser.add_argument(
        "--learning-rate",
        type=float,
        default=2e-5,
        help="Learning rate"
    )
    parser.add_argument(
        "--warmup-ratio",
        type=float,
        default=0.1,
        help="Warmup ratio for learning rate scheduler"
    )
    parser.add_argument(
        "--weight-decay",
        type=float,
        default=0.01,
        help="Weight decay"
    )
    parser.add_argument(
        "--early-stopping-patience",
        type=int,
        default=3,
        help="Early stopping patience (0 to disable)"
    )
    parser.add_argument(
        "--logging-steps",
        type=int,
        default=100,
        help="Logging frequency"
    )
    parser.add_argument(
        "--eval-steps",
        type=int,
        default=500,
        help="Evaluation frequency"
    )
    parser.add_argument(
        "--save-steps",
        type=int,
        default=500,
        help="Checkpoint save frequency"
    )
    parser.add_argument(
        "--save-total-limit",
        type=int,
        default=2,
        help="Maximum number of checkpoints to keep"
    )

    # MLflow arguments
    parser.add_argument(
        "--experiment-name",
        type=str,
        default="EmotionClassifier_Finetuning",
        help="MLflow experiment name"
    )
    parser.add_argument(
        "--skip-mlflow",
        action="store_true",
        help="Skip MLflow logging"
    )

    # Other arguments
    parser.add_argument(
        "--seed",
        type=int,
        default=42,
        help="Random seed"
    )
    parser.add_argument(
        "--num-workers",
        type=int,
        default=-1,
        help="Number of data loader workers (-1 for auto)"
    )

    return parser.parse_args()


def main() -> None:
    args = parse_args()

    # Set seed for reproducibility
    set_seed(args.seed)

    # Detect runtime
    runtime = detect_runtime(args.num_workers)
    logger.info(f"Runtime: device={runtime['device']} bf16={runtime['bf16']} fp16={runtime['fp16']}")

    # Paths
    base_dir = Path(__file__).parent.parent
    input_path = base_dir / args.input
    output_dir = base_dir / args.output_dir
    output_dir.mkdir(parents=True, exist_ok=True)

    # Load data
    logger.info(f"Loading labeled reviews from {input_path}...")
    df = pd.read_parquet(input_path)
    logger.info(f"Total reviews: {len(df):,}")

    # Filter by confidence
    df = df[df['emotion_score'] >= args.min_confidence]
    logger.info(f"After confidence filter (>= {args.min_confidence}): {len(df):,}")

    # Filter out empty texts
    df = df[df['review_text'].notna() & (df['review_text'].str.strip() != '')]
    logger.info(f"After removing empty texts: {len(df):,}")

    # Map emotions to labels
    df['label'] = df['emotion'].map(LABEL2ID)

    # Check for unmapped labels
    if df['label'].isna().any():
        unmapped = df[df['label'].isna()]['emotion'].unique()
        logger.warning(f"Unmapped emotions: {unmapped}")
        df = df.dropna(subset=['label'])

    df['label'] = df['label'].astype(int)

    # Split test set FIRST from original distribution (reflects real-world deployment)
    train_val_df, test_df = train_test_split(
        df, test_size=args.test_size, random_state=args.seed, stratify=df['label']
    )
    logger.info(f"Test set (original distribution): {len(test_df):,} samples")
    logger.info(f"Test set distribution:\n{test_df['emotion'].value_counts()}")

    # Balance training data: cap classes at max_samples_per_class
    max_per_class = args.max_samples_per_class
    logger.info(f"Balancing train/val data (max {max_per_class:,} per class)...")
    train_val_df = train_val_df.groupby('emotion').apply(
        lambda x: x.sample(min(len(x), max_per_class), random_state=args.seed)
    ).reset_index(drop=True)
    logger.info(f"After balancing train/val: {len(train_val_df):,} reviews")
    logger.info(f"Train/val distribution:\n{train_val_df['emotion'].value_counts()}")

    # Split train/val
    train_df, val_df = train_test_split(
        train_val_df, test_size=args.val_size, random_state=args.seed, stratify=train_val_df['label']
    )

    # Plot class distribution (training data)
    dist_plot_path = plot_class_distribution(train_df, 'emotion', output_dir, "Training Data Emotion Distribution")
    logger.info(f"Class distribution plot saved to {dist_plot_path}")

    data_stats = {
        "total_samples": len(df),
        "train_samples": len(train_df),
        "val_samples": len(val_df),
        "test_samples": len(test_df),
        "emotion_distribution": df['emotion'].value_counts().to_dict(),
    }

    logger.info(f"Split sizes: Train={len(train_df):,} Val={len(val_df):,} Test={len(test_df):,}")

    # Save data stats
    stats_path = output_dir / "data_stats.json"
    with open(stats_path, "w") as f:
        json.dump(data_stats, f, indent=2)

    # Convert to HuggingFace datasets
    def to_dataset(dataframe: pd.DataFrame) -> Dataset:
        return Dataset.from_pandas(
            dataframe[['review_text', 'label']].rename(columns={'review_text': 'text'}),
            preserve_index=False
        )

    dataset = DatasetDict({
        'train': to_dataset(train_df),
        'validation': to_dataset(val_df),
        'test': to_dataset(test_df),
    })

    # Load tokenizer and model
    logger.info(f"Loading tokenizer and model: {args.base_model}")
    tokenizer = AutoTokenizer.from_pretrained(args.base_model)

    def tokenize(examples):
        return tokenizer(
            examples['text'],
            truncation=True,
            max_length=args.max_length,
            padding=False,
        )

    logger.info("Tokenizing datasets...")
    tokenized_dataset = dataset.map(tokenize, batched=True, remove_columns=['text'])

    # Load model
    model = AutoModelForSequenceClassification.from_pretrained(
        args.base_model,
        num_labels=len(LABEL2ID),
        id2label=ID2LABEL,
        label2id=LABEL2ID,
    )

    # Data collator
    data_collator = DataCollatorWithPadding(tokenizer=tokenizer)

    # Training arguments
    training_args = TrainingArguments(
        output_dir=str(output_dir / "checkpoints"),
        learning_rate=args.learning_rate,
        per_device_train_batch_size=args.batch_size,
        per_device_eval_batch_size=args.batch_size * 2,
        num_train_epochs=args.epochs,
        weight_decay=args.weight_decay,
        eval_strategy="steps",
        eval_steps=args.eval_steps,
        save_strategy="steps",
        save_steps=args.save_steps,
        save_total_limit=args.save_total_limit,
        load_best_model_at_end=True,
        metric_for_best_model="f1_macro",
        greater_is_better=True,
        logging_steps=args.logging_steps,
        warmup_ratio=args.warmup_ratio,
        bf16=runtime["bf16"],
        fp16=runtime["fp16"],
        dataloader_num_workers=runtime["num_workers"],
        dataloader_pin_memory=runtime["pin_memory"],
        report_to="none",
        seed=args.seed,
    )

    # Callbacks
    callbacks = []
    if args.early_stopping_patience > 0:
        callbacks.append(
            EarlyStoppingCallback(early_stopping_patience=args.early_stopping_patience)
        )

    # Trainer
    trainer = Trainer(
        model=model,
        args=training_args,
        train_dataset=tokenized_dataset['train'],
        eval_dataset=tokenized_dataset['validation'],
        #tokenizer=tokenizer,
        data_collator=data_collator,
        compute_metrics=compute_metrics,
        callbacks=callbacks,
    )

    # Save training config
    config = {
        "base_model": args.base_model,
        "max_length": args.max_length,
        "batch_size": args.batch_size,
        "epochs": args.epochs,
        "learning_rate": args.learning_rate,
        "warmup_ratio": args.warmup_ratio,
        "weight_decay": args.weight_decay,
        "early_stopping_patience": args.early_stopping_patience,
        "seed": args.seed,
        "emotions": EMOTIONS,
        "label2id": LABEL2ID,
        "id2label": ID2LABEL,
        "runtime": runtime,
    }
    config_path = output_dir / "training_config.json"
    with open(config_path, "w") as f:
        json.dump(config, f, indent=2, default=str)

    # Train
    logger.info("Starting training...")
    print("\n" + "=" * 60)
    print("TRAINING CONFIGURATION")
    print("=" * 60)
    print(json.dumps(config, indent=2, default=str))
    print("=" * 60 + "\n")

    start_time = time.time()
    trainer.train()
    training_time = time.time() - start_time
    logger.info(f"Training completed in {training_time:.2f} seconds ({training_time/60:.2f} minutes)")

    # Evaluate on test set
    test_metrics = evaluate_on_test_set(trainer, tokenized_dataset['test'], output_dir)

    # Save final model
    final_model_path = output_dir / "final"
    trainer.save_model(str(final_model_path))
    tokenizer.save_pretrained(str(final_model_path))
    logger.info(f"Model saved to {final_model_path}")

    # Save test set for later evaluation
    test_df.to_parquet(output_dir / "test_set.parquet", index=False)

    # Save run summary
    run_summary = {
        "training_time_seconds": training_time,
        "training_time_minutes": training_time / 60,
        "data_stats": data_stats,
        "test_metrics": test_metrics,
        "config": config,
        "model_path": str(final_model_path),
        "timestamp": datetime.now().isoformat(),
    }
    summary_path = output_dir / "run_summary.json"
    with open(summary_path, "w") as f:
        json.dump(run_summary, f, indent=2, default=str)
    logger.info(f"Run summary saved to {summary_path}")

    # Log to MLflow
    mlflow_run_id = None
    if not args.skip_mlflow and check_mlflow_env():
        run_name = f"emotion_clf_{args.base_model.split('/')[-1]}_{datetime.now().strftime('%Y%m%d_%H%M%S')}"
        try:
            mlflow_run_id = log_to_mlflow(
                args=args,
                runtime=runtime,
                data_stats=data_stats,
                training_time=training_time,
                test_metrics=test_metrics,
                output_path=output_dir,
                run_name=run_name,
            )
        except Exception as e:
            logger.warning(f"MLflow logging failed: {e}")

    # Print final summary
    print("\n" + "=" * 60)
    print("TRAINING COMPLETE")
    print("=" * 60)
    print(f"Training time: {training_time/60:.2f} minutes")
    print(f"Test accuracy: {test_metrics['test_accuracy']:.4f}")
    print(f"Test F1 (weighted): {test_metrics['test_f1_weighted']:.4f}")
    print(f"Test F1 (macro): {test_metrics['test_f1_macro']:.4f}")
    print(f"Model saved to: {final_model_path}")
    if mlflow_run_id:
        print(f"MLflow run ID: {mlflow_run_id}")
    print("=" * 60)


if __name__ == "__main__":
    main()
